# Generated by Django 2.1.7 on 2019-04-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='mobile',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mobile'),
        ),
    ]
