# Generated by Django 2.1.7 on 2019-04-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0003_auto_20190412_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='action',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='action_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
