# Generated by Django 2.1.7 on 2019-04-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0004_auto_20190415_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='lead_course', to='SiriusCRM.LeadCourse'),
            preserve_default=False,
        ),
    ]
