# Generated by Django 2.1.7 on 2019-04-18 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0005_auto_20190417_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='appointmentstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contactcomment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='contactsocial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='coursecurator',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='crmcomment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leadcomment',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leadcourse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leadsource',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='leadstatus',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organizationincome',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='organizationoutcome',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usercategory',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usercompetency',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usercourse',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usercourseessay',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userfaculty',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='useroffline',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userposition',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='usersocial',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='userunit',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='zdravnizacomment',
            options={'ordering': ['id']},
        ),
    ]
