# Generated by Django 2.1.7 on 2019-04-22 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0006_auto_20190418_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
