# Generated by Django 2.1.7 on 2019-04-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0007_lead_date_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['date_added', 'id']},
        ),
    ]
