# Generated by Django 2.1.7 on 2019-04-23 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0010_auto_20190423_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='messenger',
        ),
    ]
