# Generated by Django 2.1.7 on 2019-04-24 08:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0011_remove_lead_messenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='date_added',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
