# Generated by Django 2.1.7 on 2019-04-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0013_auto_20190424_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_value', to='SiriusCRM.ZdravnizaComment'),
        ),
        migrations.AlterField(
            model_name='contactcomment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_value', to='SiriusCRM.Contact'),
        ),
        migrations.AlterField(
            model_name='contactmessenger',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messenger_value', to='SiriusCRM.Contact'),
        ),
        migrations.AlterField(
            model_name='contactmessenger',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messenger_value', to='SiriusCRM.Messenger'),
        ),
        migrations.AlterField(
            model_name='contactsocial',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_social', to='SiriusCRM.Contact'),
        ),
        migrations.AlterField(
            model_name='contactsocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_social_value', to='SiriusCRM.Social'),
        ),
        migrations.AlterField(
            model_name='coursecurator',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_curator', to='SiriusCRM.Position'),
        ),
        migrations.AlterField(
            model_name='coursecurator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_curator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leadmessenger',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_messenger_value', to='SiriusCRM.Lead'),
        ),
        migrations.AlterField(
            model_name='leadmessenger',
            name='messenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_messenger_value', to='SiriusCRM.Messenger'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_value', to='SiriusCRM.Category'),
        ),
        migrations.AlterField(
            model_name='usercategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_category', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercompetency',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_value', to='SiriusCRM.Competency'),
        ),
        migrations.AlterField(
            model_name='usercompetency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_competency', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_value', to='SiriusCRM.Course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercourseessay',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_essay', to='SiriusCRM.Course'),
        ),
        migrations.AlterField(
            model_name='usercourseessay',
            name='essay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_value', to='SiriusCRM.Essay'),
        ),
        migrations.AlterField(
            model_name='usercourseessay',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_course_essay', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfaculty',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_value', to='SiriusCRM.Faculty'),
        ),
        migrations.AlterField(
            model_name='userfaculty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useroffline',
            name='offline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_value', to='SiriusCRM.Offline'),
        ),
        migrations.AlterField(
            model_name='useroffline',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_offline', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_value', to='SiriusCRM.Position'),
        ),
        migrations.AlterField(
            model_name='userposition',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='social',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_value', to='SiriusCRM.Social'),
        ),
        migrations.AlterField(
            model_name='usersocial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_value', to='SiriusCRM.Unit'),
        ),
        migrations.AlterField(
            model_name='userunit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unit', to=settings.AUTH_USER_MODEL),
        ),
    ]
