# Generated by Django 2.1.7 on 2019-04-25 18:34

import SiriusCRM.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0014_auto_20190424_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultant',
            field=models.ForeignKey(default=1, on_delete=models.SET(SiriusCRM.models.get_zdravniza_consultant), related_name='appointment_consultant', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
