# Generated by Django 2.1.7 on 2019-05-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0017_auto_20190514_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(auto_now_add=True, verbose_name='Date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_left',
            field=models.DateField(blank=True, null=True, verbose_name='Date left'),
        ),
    ]
