# Generated by Django 2.1.7 on 2019-05-14 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiriusCRM', '0018_auto_20190514_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateField(default=datetime.date.today, verbose_name='Date joined'),
        ),
    ]
