# Generated by Django 2.1.7 on 2019-05-27 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0008_city_timezone'),
        ('SiriusCRM', '0019_auto_20190514_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lead_city', to='cities_light.City'),
        ),
    ]
