from SiriusCRM.models import Country, Region

rus = Country.objects.filter(name='Россия')[0]
kaz = Country.objects.filter(name='Казахстан')[0]

Region.objects.create(id=1101, name='Алтайский край', country=rus)
Region.objects.create(id=1103, name='Краснодарский край', country=rus)
Region.objects.create(id=1104, name='Красноярский край', country=rus)
Region.objects.create(id=1105, name='Приморский край', country=rus)
Region.objects.create(id=1107, name='Ставропольский край', country=rus)
Region.objects.create(id=1108, name='Хабаровский край', country=rus)
Region.objects.create(id=1110, name='Амурская область', country=rus)
Region.objects.create(id=1111, name='Архангельская область', country=rus)
Region.objects.create(id=1112, name='Астраханская область', country=rus)
Region.objects.create(id=1114, name='Белгородская область', country=rus)
Region.objects.create(id=1115, name='Брянская область', country=rus)
Region.objects.create(id=1117, name='Владимирская область', country=rus)
Region.objects.create(id=1118, name='Волгоградская область', country=rus)
Region.objects.create(id=1119, name='Вологодская область', country=rus)
Region.objects.create(id=1120, name='Воронежская область', country=rus)
Region.objects.create(id=1122, name='Нижегородская область', country=rus)
Region.objects.create(id=1124, name='Ивановская область', country=rus)
Region.objects.create(id=1125, name='Иркутская область', country=rus)
Region.objects.create(id=1127, name='Калининградская область', country=rus)
Region.objects.create(id=1128, name='Тверская область', country=rus)
Region.objects.create(id=1129, name='Калужская область', country=rus)
Region.objects.create(id=1130, name='Камчатский край', country=rus)
Region.objects.create(id=1132, name='Кемеровская область', country=rus)
Region.objects.create(id=1133, name='Кировская область', country=rus)
Region.objects.create(id=1134, name='Костромская область', country=rus)
Region.objects.create(id=1136, name='Самарская область', country=rus)
Region.objects.create(id=1137, name='Курганская область', country=rus)
Region.objects.create(id=1138, name='Курская область', country=rus)
Region.objects.create(id=1140, name='Санкт-Петербург', country=rus)
Region.objects.create(id=1141, name='Ленинградская область', country=rus)
Region.objects.create(id=1142, name='Липецкая область', country=rus)
Region.objects.create(id=1144, name='Магаданская область', country=rus)
Region.objects.create(id=1145, name='Moscow;Москва', country=rus)
Region.objects.create(id=1146, name='Московская область', country=rus)
Region.objects.create(id=1147, name='Мурманская область', country=rus)
Region.objects.create(id=1149, name='Новгородская область', country=rus)
Region.objects.create(id=1150, name='Новосибирская область', country=rus)
Region.objects.create(id=1151, name='Ненецкий автономный округ', country=rus)
Region.objects.create(id=1152, name='Омская область', country=rus)
Region.objects.create(id=1153, name='Оренбургская область', country=rus)
Region.objects.create(id=1154, name='Орловская область', country=rus)
Region.objects.create(id=1156, name='Пензенская область', country=rus)
Region.objects.create(id=1157, name='Пермский край', country=rus)
Region.objects.create(id=1158, name='Псковская область', country=rus)
Region.objects.create(id=1160, name='Ростовская область', country=rus)
Region.objects.create(id=1161, name='Рязанская область', country=rus)
Region.objects.create(id=1162, name='Ханты-Мансийский автономный округ', country=rus)
Region.objects.create(id=1163, name='Саратовская область', country=rus)
Region.objects.create(id=1164, name='Сахалинская область', country=rus)
Region.objects.create(id=1165, name='Свердловская область', country=rus)
Region.objects.create(id=1166, name='Смоленская область', country=rus)
Region.objects.create(id=1168, name='Тамбовская область', country=rus)
Region.objects.create(id=1169, name='Томская область', country=rus)
Region.objects.create(id=1170, name='Тульская область', country=rus)
Region.objects.create(id=1171, name='Тюменская область', country=rus)
Region.objects.create(id=1172, name='Ямало-Ненецкий автономный округ', country=rus)
Region.objects.create(id=1173, name='Ульяновская область', country=rus)
Region.objects.create(id=1174, name='Ингушетия Республика', country=rus)
Region.objects.create(id=1175, name='Челябинская область', country=rus)
Region.objects.create(id=1176, name='Забайкальский край', country=rus)
Region.objects.create(id=1177, name='Чукотский автономный округ', country=rus)
Region.objects.create(id=1178, name='Ярославская область', country=rus)
Region.objects.create(id=1179, name='Адыгея Республика', country=rus)
Region.objects.create(id=1180, name='Башкортостан Республика', country=rus)
Region.objects.create(id=1181, name='Бурятия Республика', country=rus)
Region.objects.create(id=1182, name='Дагестан Республика', country=rus)
Region.objects.create(id=1183, name='Кабардино-Балкария Республика', country=rus)
Region.objects.create(id=1184, name='Алтай Республика', country=rus)
Region.objects.create(id=1185, name='Калмыкия Республика', country=rus)
Region.objects.create(id=1186, name='Карелия Республика', country=rus)
Region.objects.create(id=1187, name='Коми Республика', country=rus)
Region.objects.create(id=1188, name='Марий-Эл Республика', country=rus)
Region.objects.create(id=1189, name='Мордовия Республика', country=rus)
Region.objects.create(id=1190, name='Северная Осетия Республика', country=rus)
Region.objects.create(id=1191, name='Карачаево-Черкесия Республика', country=rus)
Region.objects.create(id=1192, name='Татарстан Республика', country=rus)
Region.objects.create(id=1193, name='Тыва Республика', country=rus)
Region.objects.create(id=1194, name='Удмуртия Республика', country=rus)
Region.objects.create(id=1195, name='Хакасия Республика', country=rus)
Region.objects.create(id=1196, name='Чеченская Республика', country=rus)
Region.objects.create(id=1197, name='Чувашия Республика', country=rus)
Region.objects.create(id=1198, name='Саха (Якутия) Республика', country=rus)
Region.objects.create(id=1199, name='Еврейский автономный округ', country=rus)

Region.objects.create(id=11, name='Акмолинская область', country=kaz)
Region.objects.create(id=15, name='Актюбинская область', country=kaz)
Region.objects.create(id=19, name='Алматинская область', country=kaz)
Region.objects.create(id=23, name='Атырауская область', country=kaz)
Region.objects.create(id=27, name='Западно-Казахстанская область', country=kaz)
Region.objects.create(id=31, name='Жамбылская область', country=kaz)
Region.objects.create(id=35, name='Карагандинская область', country=kaz)
Region.objects.create(id=39, name='Костанайская область', country=kaz)
Region.objects.create(id=43, name='Кызылординская область', country=kaz)
Region.objects.create(id=47, name='Мангистауская область', country=kaz)
Region.objects.create(id=51, name='Южно-Казахстанская область', country=kaz)
Region.objects.create(id=55, name='Павлодарская область', country=kaz)
Region.objects.create(id=59, name='Северо-Казахстанская область', country=kaz)
Region.objects.create(id=63, name='Восточно-Казахстанская область', country=kaz)
Region.objects.create(id=71, name='Астана', country=kaz)
Region.objects.create(id=75, name='Алмата', country=kaz)